export const SET_POST_CREATION_PENDING = 'SET_POST_CREATION_PENDING';
export const SET_POST_CREATION_SUCCESS = 'SET_POST_CREATION_SUCCESS';
export const SET_POST_CREATION_ERROR = 'SET_POST_CREATION_ERROR';
